# Change these first
owner: Zspace Servers
repo: Uptime-Monitor

sites:
  - name: Main Website
    url: https://zspaceservers.com
  - name: Forums Website
    url: https://forums.zspaceservers.com
  - name: Status Website
    url: https://status.zspaceservers.com
  - name: Panel Website
    url: https://panel.zspaceservers.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.zspaceservers.com
  # baseUrl: /your-repo-name
  logoUrl: https://zspaceservers.com/home/images/logo.png
  name: Uptime
  introTitle: "Zspace Servers"
  introMessage: Status of any of our Websites or Nodes
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
